#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

path=(
  $HOME/bin
  $path
)

# Aliases
alias reload!='. ~/.zshrc'
alias hgrep='history | grep'
alias sctl='supervisorctl'

# FileSearch
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -R . }

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }

# RVM - Ruby Version Manager
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# NVM - Node Version Manager
# Node installs will be lost upon upgrading nvm. Add the following above
# the source line to move install location and prevent this:
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# Completions
# Cache expiration days for grunt completion
zstyle ':completion::complete:grunt::options:' expire 1

# localrc (machine specific shell config)
[ -e $HOME/.localrc ] && source $HOME/.localrc